name: Exemplo basico de Github Actions
on: [push]
jobs:
  job_01:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando job 01"
  job_02:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando job 02"
